### ISSUE TITLE
CPU 사용량의 뷰를 변경할 수 있게 해주세요.

### ISSUE THREAD

**Issue by sunghun7511** [sunghun7511/gotop#9]
## 어떤 내용인가요?

기본적으로 CPU 전체 사용량을 보여주고, 특정 키를 눌러 개별 CPU의 사용량을 각각 보여주도록 해주세요

**Comment by calofmijuck** [comment]
`top` 의 구현대로 <kbd>1</kbd> 을 누르면 각 cpu 코의 사용량을 보여주도록 하겠습니다.
